workspace:
  base: /go
  path: src/toroid.io/drone-plugins/drone-mella

pipeline:
  buildgo:
    image: golang:1.10
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: plugins/docker
    repo: toroid/drone-mella
    tags: latest
    when:
      branch: master
      event: deployment
      environment: production
    secrets: [docker_username, docker_password]

  test:
    image: plugins/docker
    repo: toroid/drone-mella
    tags: ${DRONE_DEPLOY_TO}
    when:
      event: deployment
      environment:
        exclude: production
    secrets: [docker_username, docker_password]
